config/routes.rb
Rails.application.routes.draw do
  
  get 'messages/index'
  get 'conversations/index'
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :participations
  end
  resources :categories
  resources :team, only: [:index] 
  resources :users do
    member do
      put "like" => "users#upvote"
      put "unlike" => "users#downvote"
    end
  end

  resources :users
	  scope 'admin', module: 'admin', as: 'admin' do
    resources :landing, only: [:index]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :posts, only: [:create, :index, :edit, :update, :destroy]
    root 'landing#index'
  end
    
  
  resources :cgu, only: [:index]
  resources :privacy, only: [:index]
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates :user_id, uniqueness: {scope: :post_id}
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

    before_action :authenticate_user!, only: [:create]

    def new
        participation = Participation.new
        @post = Post.find(params[:post_id])
    end

    def show
        @participation = Participation.find(params[:id])        
    end

    def create
        @post = Post.find(params[:post_id])
        @participation = Participation.new(user_id: current_user.id, post_id: @post.id)

        if @participation.save
            flash[:notice] = "Vous êtes bien inscrit"
            redirect_to post_path(@post) 
        else
            redirect_to post_path(@post) 
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @participation = Participation.find_by(user_id: current_user.id, post_id: @post)
        @participation.destroy

        if @participation.delete
            flash[:success] = "Vote participation a bien été supprimé"
            redirect_to post_path(@post) 
        else
            flash[:danger] = "Votre participation n'a pas pu être supprimé, veuillez rééssayer ultérieurement"
            redirect_to root_path
        end
    end      
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/new.html.erb
<div class="card">
  <div class="card-body text-center">
  <h2> Confirmer votre participation : </h2>
        <%= form_tag post_participations_path(@post) do %>
            <article>
                <%= submit_tag "Confirmer", class: 'btn btn-outline-primary btn-sm'%>
                <%= link_to "Revenir à l'accueil", root_path, class: 'btn btn-outline-info btn-sm', style: 'margin-right: 10px' %>
            </article>
        <% end %>

        <%= image_tag("https://image.freepik.com/vecteurs-libre/illustration-concept-ok_114360-2060.jpg") %>

    </div>
</div>

app/views/participations/show.html.erb
<h2> Votre participation a été enregistrée </h2>
<%= link_to "Revenir à l'accueil", root_path, class: 'btn btn-outline-warning btn-sm', style: 'margin-right: 10px' %>