config/routes.rb
Rails.application.routes.draw do
  
  get 'messages/index'
  get 'conversations/index'
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :participations
  end
  resources :categories
  resources :team, only: [:index] 
  resources :users do
    member do
      put "like" => "users#upvote"
      put "unlike" => "users#downvote"
    end
  end

  resources :users
	  scope 'admin', module: 'admin', as: 'admin' do
    resources :landing, only: [:index]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :posts, only: [:create, :index, :edit, :update, :destroy]
    root 'landing#index'
  end
    
  
  resources :cgu, only: [:index]
  resources :privacy, only: [:index]
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_votable
  acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
       has_many :created_posts, class_name: 'Post'
       has_many :participations
       has_many :answered_posts, through: :participations, source: :post
       validates :first_name, presence: true
       validates :last_name, presence: true
         
       after_create :welcome_send

       def welcome_send
              UserMailer.welcome_email(self).deliver_now
       end
end

app/controllers/admin/users_controller.rb
module Admin

  class UsersController < ApplicationController
    def index
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user=User.find(params[:id])

      first_name = params[:user][:first_name]
      last_name = params[:user][:last_name]
      email = params[:user][:email]
      admin_value = params[:user][:is_admin]
        @user.update(first_name:first_name,last_name:last_name, email:email)
        if admin_value == "1"
          @user.update(is_admin:true)
        else
            @user.update(is_admin:false)
        end
        redirect_to admin_users_path
    end

      def destroy
      @user=User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :user_is_allowed_to_vote?
  
  def show
  if User.exists?(params[:id])
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end


  def upvote
    @user = User.find(params[:id])
    @user.upvote_from current_user
		respond_to do |format|
       format.html { redirect_to user_path(@user.id) }
       format.js { }
	      end
  end

  def downvote
    @user = User.find(params[:id])
    @user.downvote_from current_user
  	    respond_to do |format|
       format.html { redirect_to user_path(@user.id) }
       format.js { }
        end
  end

  private

	def user_is_allowed_to_vote?
		current_user.answered_posts.where(user:@user).present? || @user.answered_posts.where(user:current_user).present?
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/downvote.js.erb
document.getElementsByClassName('badge')[0].innerHTML="<%= @user.get_upvotes.size %>";
document.getElementsByClassName('badge')[1].innerHTML="<%= @user.get_downvotes.size %>";

app/views/users/show.html.erb
<div class = "col-md-5 col-lg-5 mt-5">
  <%= link_to "Revenir à l'accueil", root_path, class: 'btn btn-info btn-sm', style: 'margin-right: 10px' %>
</div>
<div class="row">
  <div class = "col-md-10 col-lg-6 d-flex flex-column mt-1">
    <% if user_signed_in? && current_user.id == @user.id %>
      <%= image_tag("https://comhelp.s3.eu-west-3.amazonaws.com/comhelp/Page+profile/page+profile.jpg") %>
      <div class = "col-md-5 col-lg-5 d-flex flex-column mt-1">
        <%= link_to "Créer une nouvelle annonce", new_post_path,  :class => "btn btn-outline-primary text-center pull-right" %>
      </div>
    <%else%>
      <%= image_tag("https://comhelp.s3.eu-west-3.amazonaws.com/comhelp/Page+profile/page+profile+visiteur.jpg") %>
    <% end %>
  </div>
    <div class="col-md-4">
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="card border">
          <div class="card-body">
            <h2 class="text-primary mt-3"><b>Mon profile :</b></h2>
              <hr>
                <p class="text-dark mt-3"><b>Prénom</b> : <%= @user.first_name %></p>
                <p class="text-dark mt-3"><b>Nom</b> : <%= @user.last_name %></p>
                <p class="text-dark mt-3"><b>E-mail</b> : <%= @user.email %></p>
                <p class="text-dark mt-3"><b>Nombre d'avis favorables / défavorables</b></p> 
                <span>
                  <button type="button" class="like btn btn-outline-primary no-click">
                    <i class="far fa-thumbs-up" aria-hidden="true"></i>
                    <span class="badge"><%= @user.get_upvotes.size %></span>
                  </button>
                </span>
                <span>
                  <button type="button" class="like btn btn-outline-danger no-click">
                    <i class="far fa-thumbs-down" aria-hidden="true"></i>
                    <span class="badge"><%= @user.get_downvotes.size %></span>
                  </button>
                </span>
                <hr>
                  <p class="profile-pad">Je souhaite modifier mes données personnelles ou mon mot de passe ?</p>
                       <%= link_to "C'est par ici !", edit_user_registration_path(@user.id), class: 'btn btn-primary profile-btn' %>
                    <hr>
                      <p class="profile-pad">Accéder à votre messagerie en cliquant juste ici :</p>
                      <p><%= link_to "Ma messagerie", conversations_index_path, :class => "btn btn-info"  %></p>
              </div>
          </div>
          <% else %>
          <div class="card border">
            <div class="card-body">
              <h2 class ="text-primary mt-3"><b>Vous êtes sur le profile de <%= @user.first_name %> :</b></h2>
              <hr>
                <p class="text-dark mt-3"><b>Prénom</b> : <%= @user.first_name %></p>
                <p class="text-dark mt-3"><b>Nom</b> : <%= @user.last_name %></p>
                  <% if user_signed_in? && user_is_allowed_to_vote? && ! current_user.find_voted_items.include?(@user) %>
                      <%= link_to like_user_path(@user), method: :put, remote: true do %>
                        <span>
                          <button type="button" class="like btn btn-primary">
                            <i class="far fa-thumbs-up" aria-hidden="true"></i>
                          <span class="badge"><%= @user.get_upvotes.size %></span>
                          </button>
                        </span>
                      <% end %>
                     <%= link_to unlike_user_path(@user), method: :put, remote: true do %>
                        <span>
                          <button type="button" class="dislike btn btn-danger">
                            <i class="far fa-thumbs-down" aria-hidden="true"></i>
                          <span class="badge"><%= @user.get_downvotes.size %></span>
                          </button>
                        </span>
                     <% end %>
                    <h6><b>Veuillez noter cet utilisateur en cliquant sur l'une des deux icônes.</b></h6>                 
                    <% else %>
                     <div class="text-dark mt-3"><b>Nombre d'avis favorables / défavorables</b>
                        <span>
                          <button type="button" class="like btn btn-outline-primary no-click">
                            <i class="far fa-thumbs-up" aria-hidden="true"></i>
                            <span class="badge"><%= @user.get_upvotes.size %></span>
                          </button>
                        </span>
                        <span>
                          <button type="button" class="dislike btn btn-outline-danger no-click">
                            <i class="far fa-thumbs-down" aria-hidden="true"></i>
                            <span class="badge"><%= @user.get_downvotes.size %></span>
                          </button>
                        </span>
                      </div>
                      <p><small> * Vous ne pouvez attribuer un vote à un utilisateur que s'il répondu à une de vos annonces ou posté une annonce à laquelle vous avez répondu.</small></p>
                      <P><small> * Vous ne pouvez pas voter deux fois.</small></p>

                    <% end %>
                  </ul>
              <hr>
              <h6 class="profile-pad">Vous souhaitez envoyer un message privé à <%= @user.first_name %> ?</h6>
              <%= link_to "Envoyer un message",  conversations_path(sender_id: current_user.id,  receiver_id: @user), method: 'post', class: 'btn btn-primary profile-btn' %>
            </div>
          </div>
      <% end %>
        <hr>
    
      <% if user_signed_in? && current_user.id == @user.id %>
        <p><b>Mes annonces :</b></p>
            <ul>
              <% @user.created_posts.each do |post| %>
                <li><%= link_to "#{post.title}", post_path(post.id) %>, le <%= post.datetime %> 
                  <% if post.is_validated != true %>
                    <span class= "font-italic text-uppercase text-danger"> Votre annonce est en cours de validation </span>
                    
                  <% end %>
                </li>
              <% end %>
            </ul>
      <% else %>
          <% if @user.created_posts.count != 0 %>
            <p><b>Annonces postées par <%= @user.first_name %> :</b></p>

            <ul>
              <% @user.created_posts.each do |post| %>
              
                <li><%= link_to "#{post.title}", post_path(post.id) %>, le <%= post.datetime %> </li>
                
             <% end %>
            </ul>
          <% else %>
            <p class="lead-color"><b><%= @user.first_name %> n'a encore posté aucune annonce.</b><p>
          <% end %>
        <br>
      <% end %>
              <% if user_signed_in? && current_user.id == @user.id %>
                <p><b>Les annonces auxquelles j'ai répondu :</b></p>
                  <ul>
                    <% @user.answered_posts.each do |post| %>
                      <li><%= link_to "#{post.title}", post_path(post.id) %>, le <%= post.datetime %>, annonce postée par <%= post.user.first_name %> </li>
                    <% end %>
                  </ul>
              <% else %>
                <% if @user.answered_posts.count != 0 %>
                  <p><b>Les annonces auxquelles <%= @user.first_name %> a répondu :</b><p>
                  <ul>
                    <% @user.answered_posts.each do |post| %>
                      <li><%= link_to "#{post.title}", post_path(post.id) %>, le <%= post.datetime %>, annonce postée par <%= post.user.first_name %> </li>
                    <% end %>
                  </ul>
                <% else %>
            <p><b><%= @user.first_name %> n'a encore répondu à aucune annonce.</b><p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  

app/views/users/upvote.js.erb
document.getElementsByClassName('badge')[0].innerHTML="<%= @user.get_upvotes.size %>";
document.getElementsByClassName('badge')[1].innerHTML="<%= @user.get_downvotes.size %>";