config/routes.rb
Rails.application.routes.draw do
  
  get 'messages/index'
  get 'conversations/index'
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :participations
  end
  resources :categories
  resources :team, only: [:index] 
  resources :users do
    member do
      put "like" => "users#upvote"
      put "unlike" => "users#downvote"
    end
  end

  resources :users
	  scope 'admin', module: 'admin', as: 'admin' do
    resources :landing, only: [:index]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :posts, only: [:create, :index, :edit, :update, :destroy]
    root 'landing#index'
  end
    
  
  resources :cgu, only: [:index]
  resources :privacy, only: [:index]
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/post.rb
require 'twitter'

class Post < ApplicationRecord
   after_create :email_to_admin
	 after_commit :automatic_tweet

    belongs_to :user
    belongs_to :category
    belongs_to :city
    has_many :participations
    has_many :users, through: :participations
    
    
    validates :title, presence: true, length: { in: 5..140 }
    validates :description, presence: true, length: { in: 20..1000}
   

    def email_to_admin
	    AdminMailer.new_ad_notification(self).deliver_now
    end

    include AlgoliaSearch
    
    algoliasearch per_environment: true do
        attribute :category, :city, :title, :description
    end
    
    
    def automatic_tweet
        if self.is_validated == true
    
        client = Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
        config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
        config.access_token        = ENV["TWITTER_ACCESS_TOKEN"]
        config.access_token_secret = ENV["TWITTER_ACCESS_TOKEN_SECRET"]
      end
        client.update("Annonce postée à #{self.city.city_name} : #{self.description}")
      end
    end
end

app/controllers/admin/posts_controller.rb
module Admin

class PostsController < ApplicationController
  def index
  end

	def create
		Post.find(params[:id]).update(is_validated:true)
		redirect_to admin_posts_path
	end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post=Post.find(params[:id])

    title = params[:post][:title]
    description = params[:post][:description]
    category_id = params[:post][:category_id]
      @post.update(title:title,description:description,category_id:category_id)

      redirect_to admin_posts_path
  end

    def destroy
    @post=Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]  
  before_action :check_property_or_is_admin, only: [:edit, :update, :destroy]  
  
  def index
    @post = Post.all
    @category = Category.all
  end

  def show
    @post = Post.find_by_id(params[:id])
    @participant = Participation.where(:post_id => @post.id)  
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to root_path 
      flash[:success] = "Annonce créée avec succès!"
    else
      flash[:danger] = "Votre annonce n'a pas pu être enregistrée pour la/les raison(s) suivante(s) : #{@post.errors.full_messages.each {|message| message}.join('')}"
      redirect_to controller: 'posts', :action => 'new'

    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path(@post.id), notice => "Votre post a été mis a jour"
    else
      flash[:danger] = "Votre annonce n'a pas pu être modifiée pour la/les raison(s) suivante(s) : #{@post.errors.full_messages.each {|message| message}.join('')}"
      render "edit"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, :notice => "Votre post a été supprimé"
  end

  def owned_post  
    unless current_user == @post.user
      flash[:alert] = "Vous n'êtes pas propriétaire de ce post!"
      redirect_to root_path
      
    end  
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :category_id, :datetime, :city_id)
  end

  def check_property_or_is_admin
    @post = Post.find(params[:id])
    if current_user.id != @post.user_id && !current_user.is_admin
      flash[:alert] = "Vous n'êtes pas propriétaire de ce post !"
      redirect_to root_path
    end  
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/edit.html.erb
    <div class="form-control-lg text-center w-100 vh-100">
        <h1 class="text-primary">Modifie ton annonce</h1>
            <div class= "d-flex flex-column">
                <div class="w-100 p-4 h-75">
                    <div class="form mx-auto">
                        <%= form_for @post do |form| %>
                            <div class=" d-flex flex-row justify-content-around bg-dark-grad text-light w-75 mx-auto" > 
                            <div class="field">
                                <%= form.label :Categorie, :class => "mb-0 mt-2" %></br>
                                <%= form.collection_select :category_id, Category.order(:name), :id, :name, :class => "" %>
                            </div>
                            <div class="form-group mb-3">
                                <%= form.label :date, :class => "mb-0 mt-2 text-center"  %></br>
                                <%= form.date_field :datetime, autofocus: true, autocomplete: "datetime " %>
                            </div>  
                            <div class="field">
                                <%= form.label :Ville, :class => "mb-0 mt-2 text-center"  %></br>
                                <%= form.collection_select :city_id, City.order(:city_name), :id, :city_name%>
                            </div>
                        </div>
                        <div>
                            <div class="field mb-3 ">
                                <%= form.label :titre, :class => "mb-0 mt-2"  %></br>
                                <%= form.text_field :title, :class => "form-control form-control-md text-center w-75 mx-auto"%>
                            </div>
                                                        
                            <div class="field">
                                <%= form.label :description, :class => "mb-0 mt-2"  %></br>
                                <%= form.text_area :description, :class => "form-control form-control-lg text-center w-75 mx-auto" %>
                            </div>
                        </div>
                                                        
                        <div class="actions ml-4 mt-4">
                            <%= form.submit "Modifier", :class => "btn btn-primary"%>
                        </div>
                        <% end %>
                    </div>
                </div> 
            </div>
    </div>

app/views/posts/index.html.erb
<section class="p-0 height-700 parallax-bg" style="background-image: url(https://comhelp.s3.eu-west-3.amazonaws.com/comhelp/Front/Help.jpg)">
        <div class="container h-100">
          <div class="row justify-content-between align-items-center h-100">
            <div class="col-md-8 mb-7">
                <h4 class="text-primary"> Rapprochons-nous et retrouvons-nous !</h4>
                <h1 class="display-6 font-weight-bold text-dark">ComHelp</h1>
                <div class="container pl-0">
                  <% if user_signed_in? %>
                    <%= link_to "Poster votre annonce", new_post_path,  :class => "btn btn-primary" %>
                  <% else %>
                    <%= link_to "Connectez-vous", new_user_session_path, class: 'btn btn-dark  ml-2 mr-0 text-light'%>
                  <%end%>
                </div>
            </div>
          </div>
        </div>
</section>


<section class="py-3 bg-grad counter counter-small">
		<div class="container">
			<div class="row">
				<!-- count item -->
        <div class="col-md-3 col-6">
          <div class="counter-item text-center">
            <i class="fas fa-users fa-3x"></i>
            <h2 class="counter-item-digit" data-from="0" data-to="<%=User.all.length%>" data-speed="3000" data-refresh-interval="10"><%=User.all.length%></h2>
            <p class="counter-item-text">Nombre d'helper</p>
        </div>
      </div>
        
				<!-- count item -->
        <div class="col-md-3 col-6">
        <div class="counter-item text-center">
          <i class="fas fa-scroll fa-3x"></i>
          <h2 class="counter-item-digit" data-from="0" data-to="<%=Post.all.length%>" data-speed="3000" data-refresh-interval="10"><%=Post.all.length%></h2>
          <p class="counter-item-text">Nombre d'annonces</p>
        </div>
      </div>
        
				<!-- count item -->
				<div class="col-md-3 col-6">
        <div class="counter-item text-center">
          <i class="fas fa-hands-helping fa-3x"></i>
          <h2 class="counter-item-digit" data-from="0" data-to="<%=Participation.all.length%>" data-speed="3000" data-refresh-interval="10"><%=Participation.all.length%></h2>
          <p class="counter-item-text">Nombre de Coups de mains</p>
        </div>
      </div>

				<!-- count item -->
				<div class="col-md-3 col-6">
        <div class="counter-item text-center">
          <i class="fas fa-building fa-3x"></i>
          <h2 class="counter-item-digit" data-from="0" data-to="<%=City.all.length%>" data-speed="3000" data-refresh-interval="10"><%=City.all.length%></h2>
          <p class="counter-item-text">Nombre de villes </p>
        </div>
      </div>
			</div>
		</div>
</section>

<!--Searchbox-->
  <h3 class="mt-3 ml-3">Rechercher une annonce</h3>
  <div class="right-panel mt-3 ml-3">
    <div class="row-xs-2" id="searchbox">
    
      <%= image_tag(("https://comhelp.s3.eu-west-3.amazonaws.com/comhelp/Logo/search-by-algolia-light-background.svg"))%>
    </div>
  </div>
<!-- Fin Searchbox-->

<div id="hits"></div>

<!-- Notice-->
<div class= "d-flex justify-content-around my-6 ">
    <div class = "col-md-3 mt-30 ml-5">
      <div class = "feature-box f-style-2 icon-grad h-100">
        <div class = "feature-box-icon">
          <i class="fas fa-pencil-alt"></i>
          <h3>Tu t'inscris</h3>
          <p></p>
        </div>
      </div>
    </div>

 
    <div class = "col-md-3 mt-30">
      <div class = "feature-box f-style-2 icon-grad h-100">
        <div class = "feature-box-icon">
          <i class="fas fa-question"></i>
          <h3>Tu demandes de l'aide</h3>
          <p></p>
        </div>
      </div>
    </div>
  
 
    <div class = "col-md-3 mt-30">
      <div class = "feature-box f-style-2 icon-grad h-100">
        <div class = "feature-box-icon">
          <i class="fas fa-people-carry"></i>
          <h3>Tu reçois de l'aide</h3>
          <p></p>
        </div>
      </div>
    </div>
  
</div>

<h1 class="text-center text-secondary my-5">Nos catégories</h1>

<div class="row">

  <%@category.each do |category|%>
      <ul class="mx-auto m-4 shadow px-5 list-unstyled" >
					
           
            <li><i class= "fa fa-check text-primary pl-2"></i><%= link_to category.name, category_path(category.id), :class =>"text-dark pl-2"%></li>
          
      </ul>
  <%end%>
</div>

<div class="bg-primary border-radius-3 py-3 all-text-white mt-5">
<h2 class="alt-font p-2 p-sm-3 text-center">"Seuls, nous pouvons faire si peu ; ensemble, nous pouvons faire beaucoup" <span class="text-dark">Helen Keller</span></h2>
</div>

<h1 class="text-center my-5">
<span class="text-secondary">Nos dernières annonces</span>
</h1>

<div class="row">
  <%@post.where(is_validated:true).each do |post|%>
    <div class="card mx-auto my-4 shadow" style="width: 25rem;">
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="card mb-4 shadow-sm">
            <img class="card-img" src="<%=post.category.picture_url%>" alt="Card image cap">
            <div class="card-body">
                <span class="text-primary"><p class="card-text">Titre : <%=post.title %></p></span>
                <p class="card-text">Ville : <%=post.city.city_name %></p>
                <p class="card-text">Categorie : <%=post.category.name %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                  <% if user_signed_in? %>
                    <%= link_to "Participer", new_post_participation_path(post),  :class => "btn btn-primary" %>
                  <% else %>
                    <%= link_to "Participer", new_user_session_path,  :class => "btn btn-primary" %>
                  <%end%>
                    <%= link_to "voir plus", post_path(post.id),  :class => "btn btn-outline-primary" %>
                  </div>
                </div>
            </div>    
          </div>
        </div>
      </div>      
    </div>
  <%end%>
</div>

app/views/posts/new.html.erb
<section class = "p-4 height-700 parallax-bg" style="background-image: url()">
    
    <div class="form-control-lg text-center w-100 vh-100">
    <h1 class="text-primary">Créer ton annonce</h1> 
        <div class= "d-flex flex-column">
            <div class="w-100 p-4 h-75" >
                <div class="form mx-auto">
                    <%= form_for @post do |form| %>
                        <div class=" d-flex flex-row justify-content-around bg-dark-grad text-light w-75 mx-auto" > 
                            <div class="field">
                                <%= form.label :Categorie, :class => "mb-0 mt-2" %></br>
                                <%= form.collection_select :category_id, Category.order(:name), :id, :name, :class => "" %>
                            </div>
                            <div class="form-group mb-3">
                                <%= form.label :date, :class => "mb-0 mt-2 text-center"  %></br>
                                <%= form.date_field :datetime, autofocus: true, autocomplete: "datetime " %>
                            </div>  
                            <div class="field">
                                <%= form.label :Ville, :class => "mb-0 mt-2 text-center"  %></br>
                                <%= form.collection_select :city_id, City.order(:city_name), :id, :city_name%>
                            </div>
                        </div>
                        <div>
                            <div class="field mb-3 ">
                                <%= form.label :titre, :class => "mb-0 mt-2"  %></br>
                                <%= form.text_field :title, :class => "form-control form-control-md text-center w-75 mx-auto"%>
                            </div>
                            
                            
                            <div class="field">
                                <%= form.label :description, :class => "mb-0 mt-2"  %></br>
                                <%= form.text_area :description, :class => "form-control form-control-lg text-center w-75 mx-auto" %>
                            </div>
                        </div>
                                                        
                        <div class="actions ml-4 mt-4">
                            <%= form.submit "Poster", :class => "btn btn-primary"%>
                        </div>
                    <% end %>
                </div>
            </div> 
        </div>
        
</section>

app/views/posts/show.html.erb
<body>

	<div class="left bg-primary pattern-overlay-4">
		<div class="container">
			<div class="row all-text-white">
				<div class="col-md-12 align-self-center">
					<h1 class="font-weight-bold display-4 display-md-1 mb-2 mb-md-n4 mt-9"><%=@post.category.name%></h1>
				</div>
			</div>
		</div>
	</div>

	<section>
		<div class="container h-100">
			<div class="row">
				<div class="col-md-12 col-lg-6 align-self-center ">
					<div class="title text-left">
						<h2><span class="text-primary"> <%=@post.title%> </span></h2>
						<p class="mb-0">Description : <%=@post.description%> </p>

						<div class="list-group-inline list-group-number list-unstyled mt-4">
						 <p> Nombre de Paticipants: <%= @participant.count %></p>
						Participant(s):
						<%@participant.each do |participant|%>
							<% if user_signed_in? %>
								<%= link_to participant.user.first_name, user_path(participant.user.id)%> /
							<% else %>
								<%= link_to participant.user.first_name, new_user_session_path %> /
							<%end%>
						<%end%>
						<p class="mb-0">Date : <%=@post.datetime%> </p>
						<% if user_signed_in? %>

						<p class="mb-0">Auteur : <%= link_to "#{@post.user.first_name} " "#{@post.user.last_name}", user_path(@post.user.id)%> </p>
						<% else %>
						<p class="mb-0">Auteur : <%= link_to "#{@post.user.first_name} " "#{@post.user.last_name}", new_user_session_path %> </p>

						<%end%>

						</div>
					</div>
				</div>
				<div class="col-md-10 col-lg-6 mx-md-auto align-self-center ">
					<img class="card-img" src="<%=@post.category.picture_url%>">
				<div class="position-absolute left-0 bottom-0 ml-4 ml-md-n2 mb-3">
				</div>
				</div>
			</div>
			<%= link_to "Revenir à l'accueil", root_path, class: 'btn btn-info btn-sm', style: 'margin-right: 10px' %>
			<% if user_signed_in? %>
				<% if current_user.answered_posts.all.include?(@post) %>
					<%= link_to "Annuler mon inscription", post_participation_path(@post), method: :delete, data: { confirm: 'Êtes vous sûrs? ' }, class:'btn btn-danger btn-sm' %>			
				<% else %>
					<%= link_to "Apporter son aide", new_post_participation_path(@post), class: 'btn btn-outline-primary btn-sm' %>
				<%end%>
			<% else %>
				<%= link_to "Apporter son aide", new_user_session_path, class: 'btn btn-outline-primary btn-sm' %>
			<%end%>
			<%if current_user == #{@post.user.id}%>
				<%= link_to "Mon espace personnel", user_path(:id => current_user.id), class: 'btn btn-outline-danger btn-sm', style: 'margin-right: 10px' %>
			<%end%>
			
			<% if current_user && @post.user == current_user %>
				<div>
					<p><%= link_to "Modifier", edit_post_path(@post.id), :class => "text-info pull-right" %></p><br>
					<p><%= link_to "Supprimer", @post, :confirm => "Ce post sera supprimé définitivement!", :method => :delete, :class => "text-danger pull-right" %></p>
				</div>
			<%end%>
		</section>
</body>