config/routes.rb
Rails.application.routes.draw do
  
  get 'messages/index'
  get 'conversations/index'
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :participations
  end
  resources :categories
  resources :team, only: [:index] 
  resources :users do
    member do
      put "like" => "users#upvote"
      put "unlike" => "users#downvote"
    end
  end

  resources :users
	  scope 'admin', module: 'admin', as: 'admin' do
    resources :landing, only: [:index]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :posts, only: [:create, :index, :edit, :update, :destroy]
    root 'landing#index'
  end
    
  
  resources :cgu, only: [:index]
  resources :privacy, only: [:index]
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_votable
  acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
       has_many :created_posts, class_name: 'Post'
       has_many :participations
       has_many :answered_posts, through: :participations, source: :post
       validates :first_name, presence: true
       validates :last_name, presence: true
         
       after_create :welcome_send

       def welcome_send
              UserMailer.welcome_email(self).deliver_now
       end
end

app/controllers/admin/users_controller.rb
module Admin

  class UsersController < ApplicationController
    def index
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user=User.find(params[:id])

      first_name = params[:user][:first_name]
      last_name = params[:user][:last_name]
      email = params[:user][:email]
      admin_value = params[:user][:is_admin]
        @user.update(first_name:first_name,last_name:last_name, email:email)
        if admin_value == "1"
          @user.update(is_admin:true)
        else
            @user.update(is_admin:false)
        end
        redirect_to admin_users_path
    end

      def destroy
      @user=User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :user_is_allowed_to_vote?
  
  def show
  if User.exists?(params[:id])
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end


  def upvote
    @user = User.find(params[:id])
    @user.upvote_from current_user
		respond_to do |format|
       format.html { redirect_to user_path(@user.id) }
       format.js { }
	      end
  end

  def downvote
    @user = User.find(params[:id])
    @user.downvote_from current_user
  	    respond_to do |format|
       format.html { redirect_to user_path(@user.id) }
       format.js { }
        end
  end

  private

	def user_is_allowed_to_vote?
		current_user.answered_posts.where(user:@user).present? || @user.answered_posts.where(user:current_user).present?
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Page de modification/suppression de l'utilisateur <%=@user.id%></h1>
	<br>
	<br>
		<h4>Vous pouvez modifier un ou plusieurs champs :</h4>
	<br>
		<%= form_for ([:admin, @user]), url: admin_user_path(@user.id), :method => :patch do |f| %>
  		Prénom: <%= f.text_field :first_name %><br />
  		Nom : <%= f.text_field :last_name %><br />
  		Adresse e-mail : <%= f.text_field :email %><br />
  		Cochez/décochez la case pour activer/désactiver le statut d'admin : <%= f.check_box :is_admin %><br />
  		<%= f.submit 'Valider' %>
		<% end %>
	<br>
	<br>
	<div class="card" style="width: 25rem;">
  		<div class="card-body">
			<h3>Attention, il sera impossible de revenir en arrière :</h3>
			<br>
			<h5><%= link_to "Supprimer", admin_user_path(@user.id), method: :delete %> cet utilisateur de la base de données.</h5>
  		</div>
	</div>
<br>
<br>
<p><%= link_to "Revenir", admin_users_path %> à l'index des utilisateurs.</p> 

app/views/admin/users/index.html.erb
<h1>Bienvenue sur l'interface de gestion des utilisateurs</h1>
<br>
<h3>Les utilisateurs actuellement enregistrés en BDD sont :</h3>
<br>
<% User.all.each do |user| %>
<div class="card" style="width: 25rem;">
  <div class="card-body">
    <p class="card-text">User_id : <%= user.id %></p>
    <p class="card-text">Nom complet : <%= user.first_name %> <%= user.last_name %></p>
    <p>Adresse e-mail : <%= user.email %></p>
	<p>Nombre d'annonces postées : <%= user.created_posts.all.count %></p>
	<p>Nombre d'annonces auxquelles <%= user.first_name %> a répondu : <%= user.answered_posts.all.count %></p>
	<p>Cet utilisateur est admin : <%= user.is_admin? %></p>
    <%= link_to "Modifier/supprimer cet utilisateur", edit_admin_user_path(user.id) %>
  </div>
</div>
<br>
<br>

<% end %> 

app/views/admin/users/show.html.erb
<h1>Page de modification/suppression de l'utilisateur <%=@user.id%></h1>
<br>
<h3>Données persos :</h3>

<%= form_for ([:admin, @user]), url: admin_user_path(@user.id), :method => :patch do |f| %>
  Prénom: <%= f.text_field :first_name %><br />
  Nom : <%= f.text_field :last_name %><br />
  Adresse e-mail : <%= f.text_field :email %><br />
  Admin?    : <%= f.check_box :is_admin %><br />
  <%= f.submit %>
<% end %>